# Generated by Django 4.2 on 2023-04-23 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorresPh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_torre', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='apartamentoph',
            name='ph_torre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobot_api.torresph'),
            preserve_default=False,
        ),
    ]
