# Generated by Django 4.2 on 2023-04-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0003_apartamentosph_alter_torresph_tr_torre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamentoph',
            name='ph_apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_apartamentocasa_set', to='bobot_api.apartamentosph'),
        ),
        migrations.AlterField(
            model_name='apartamentoph',
            name='ph_torre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_torre_set', to='bobot_api.torresph'),
        ),
        migrations.AlterField(
            model_name='apartamentosph',
            name='ph_apartamentocasa',
            field=models.PositiveSmallIntegerField(verbose_name='AptoCasa'),
        ),
    ]
