# Generated by Django 4.2 on 2023-04-23 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0005_alter_apartamentosph_ph_apartamentocasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamentoph',
            name='ph_apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobot_api.apartamentosph'),
        ),
        migrations.AlterField(
            model_name='apartamentoph',
            name='ph_torre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobot_api.torresph'),
        ),
    ]
