# Generated by Django 4.2 on 2023-04-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0009_alter_apartamentosph_ph_apartamentocasa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamentosph',
            name='ph_apartamentocasa',
            field=models.PositiveIntegerField(),
        ),
    ]
