# Generated by Django 4.2 on 2023-04-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0010_alter_apartamentosph_ph_apartamentocasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamentosph',
            name='ph_apartamentocasa',
            field=models.PositiveBigIntegerField(),
        ),
    ]
