# Generated by Django 4.2 on 2023-04-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0012_alter_apartamentoph_ph_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartamentoph',
            name='ph_torre',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]),
        ),
    ]
