# Generated by Django 4.2 on 2023-04-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0015_placavehiculovisita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParqueaderosVisita',
            fields=[
                ('pk_slot', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('pk_status', models.BooleanField(default=False)),
            ],
        ),
    ]
