# Generated by Django 4.2 on 2023-04-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0016_parqueaderosvisita'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoSalidaVehiculoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vi_fecha_hora_ingreso', models.DateTimeField(verbose_name='%Y-%m-%d %H:%M')),
                ('vi_fecha_hora_salida', models.DateTimeField(blank=True, null=True, verbose_name='%Y-%m-%d %H:%M')),
                ('vi_status', models.BooleanField(default=True)),
                ('pl_placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobot_api.placavehiculovisita')),
            ],
        ),
    ]
