# Generated by Django 4.2 on 2023-04-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0018_alter_ingresosalidavehiculovisita_vi_fecha_hora_ingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresosalidavehiculovisita',
            name='pk_slot',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bobot_api.parqueaderosvisita'),
            preserve_default=False,
        ),
    ]
