# Generated by Django 4.2 on 2023-04-26 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0019_ingresosalidavehiculovisita_pk_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitanteDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vd_nombre', models.CharField(max_length=50)),
                ('vd_cedula', models.PositiveBigIntegerField(unique=True)),
                ('vd_telefono', models.CharField(max_length=12)),
                ('vd_fecha', models.DateField(default=django.utils.timezone.now)),
                ('ph_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobot_api.apartamentoph')),
                ('pk_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobot_api.parqueaderosvisita')),
                ('pl_placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobot_api.placavehiculovisita')),
            ],
        ),
    ]
