# Generated by Django 4.2 on 2023-04-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0023_alter_ingresodevisita_iv_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitantedatos',
            name='ph_propietario',
        ),
        migrations.RemoveField(
            model_name='visitantedatos',
            name='pk_slot',
        ),
        migrations.RemoveField(
            model_name='visitantedatos',
            name='pl_placa',
        ),
        migrations.AddField(
            model_name='ingresodevisita',
            name='ph_propietario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bobot_api.apartamentoph'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresodevisita',
            name='pk_slot',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bobot_api.parqueaderosvisita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresodevisita',
            name='pl_placa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bobot_api.placavehiculovisita'),
            preserve_default=False,
        ),
    ]
