# Generated by Django 4.2 on 2023-04-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0024_remove_visitantedatos_ph_propietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresodevisita',
            name='iv_status',
            field=models.BooleanField(default=True),
        ),
    ]
