# Generated by Django 4.2 on 2023-04-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0026_rename_iv_status_ingresodevisita_vi_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_desc', models.CharField(max_length=10)),
                ('cn_monto', models.BigIntegerField()),
                ('cn_config', models.IntegerField()),
            ],
        ),
    ]
