# Generated by Django 4.2 on 2023-05-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0028_tipovehiculo_ingresosalidavehiculovisita_vh_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='cn_hgratis',
            field=models.IntegerField(default='60'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='cn_status',
            field=models.BooleanField(default='1'),
            preserve_default=False,
        ),
    ]
