# Generated by Django 4.2 on 2023-05-01 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0029_config_cn_hgratis_config_cn_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vi_fecha_hora_salida', models.DateTimeField(verbose_name='%Y-%m-%dT%H:%M:%s')),
                ('fa_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fa_tiempo', models.IntegerField()),
                ('ph_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobot_api.apartamentoph')),
                ('vi_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobot_api.ingresodevisita')),
            ],
        ),
    ]
