# Generated by Django 4.2 on 2023-05-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0030_facturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='fa_tiempo',
            field=models.CharField(max_length=15),
        ),
    ]
