# Generated by Django 4.2 on 2024-05-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0032_conjunto_impresora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conjunto',
            old_name='cj_tek',
            new_name='cj_tel',
        ),
    ]
