# Generated by Django 4.2 on 2024-05-19 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0033_rename_cj_tek_conjunto_cj_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresora',
            name='cg_nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
