# Generated by Django 4.2 on 2024-05-23 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0034_impresora_cg_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjunto',
            name='cj_msn',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
