# Generated by Django 4.2 on 2024-05-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0035_conjunto_cj_msn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjunto',
            name='cj_msn',
            field=models.CharField(max_length=200),
        ),
    ]
