# Generated by Django 4.2 on 2024-06-19 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0036_alter_conjunto_cj_msn'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoPension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_monto', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('pe_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pe_placa', models.CharField(max_length=7)),
                ('pe_nombre', models.CharField(max_length=50)),
                ('pe_cedula', models.PositiveBigIntegerField()),
                ('pe_fecha_ini', models.DateTimeField(default=django.utils.timezone.now, verbose_name='%Y-%m-%dT%H:%M:%s')),
                ('pe_fecha_fin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='%Y-%m-%dT%H:%M:%s')),
                ('pe_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pe_status', models.BooleanField(default=True)),
                ('pe_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobot_api.parqueaderosvisita')),
                ('pe_tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bobot_api.tipovehiculo')),
            ],
        ),
    ]
