# Generated by Django 4.2 on 2024-06-28 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0037_costopension_pension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cj_base_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cj_fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='%Y-%m-%dT%H:%M:%s')),
                ('cj_fecha_cierre', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='%Y-%m-%dT%H:%M:%s')),
                ('cj_total_pension', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('cj_total_parking', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('cj_gran_total', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('cj_usuario', models.CharField(max_length=50)),
                ('cj_status_caja', models.BooleanField(default=True)),
            ],
        ),
    ]
