# Generated by Django 4.2 on 2024-06-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0038_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='cj_fecha_cierre',
            field=models.DateTimeField(null=True, verbose_name='%Y-%m-%dT%H:%M:%s'),
        ),
    ]
