# Generated by Django 4.2 on 2024-07-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0039_alter_caja_cj_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='fa_status_caja',
            field=models.BooleanField(default=True),
        ),
    ]
