# Generated by Django 4.2 on 2024-07-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0040_facturacion_fa_status_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='pe_status_caja',
            field=models.BooleanField(default=True),
        ),
    ]
