# Generated by Django 4.2 on 2024-07-10 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0041_pension_pe_status_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='cn_hora_final',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='cn_hora_inicial',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='cn_plena_monto',
            field=models.BigIntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='cn_plena_status',
            field=models.BooleanField(default=False),
        ),
    ]
