# Generated by Django 4.2 on 2024-07-21 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0042_config_cn_hora_final_config_cn_hora_inicial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lg_usuario', models.CharField(max_length=50)),
                ('lg_fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='%Y-%m-%dT%H:%M:%s')),
                ('lg_log', models.TextField()),
            ],
        ),
    ]
