# Generated by Django 4.2 on 2024-07-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0043_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tk_id', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pension',
            name='pe_tk_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
