# Generated by Django 4.2 on 2024-07-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0044_ticketid_pension_pe_tk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresosalidavehiculovisita',
            name='in_tk_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
