# Generated by Django 4.2 on 2024-07-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bobot_api', '0045_ingresosalidavehiculovisita_in_tk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjunto',
            name='cj_mail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
